### PR TITLE
redesigned the confirmation page

### PR DESCRIPTION
**Pull request by adarshsingh87**
image

image

image

The tags scroll in the mobile view

### CODE REVIEW

**Comment by achhapolia10** [comment]
[ ] Remove the splash screen it will give wrong message to the user
[ ] Make the Confirm, pending and error panel full width

**Review by achhapolia10 — CHANGES_REQUESTED** [review]
Please make the requested changes

**Comment by achhapolia10** [comment]
And does this PR affects integration?

**Comment by adarshsingh87** [comment]
The PR doesn't affect integration.
By full width do you mean the direction to be column instead of row?

**Review by SilverSpear28 — APPROVED** [review]

**Pull request merged**
