### PR TITLE
Component/user persona

### LINKED ISSUE #99: User Persona
* Order Confirmation Page
* My orders: cards
* My vouchers: cards

where there is a list add the card view.. i have given the card design on the voucher page!

My vouchers and my orders will have a same layout! Order confirmation page will be added later.
# Submit by Wednesday

### PR DESCRIPTION
**Pull request by adarshsingh87**
Voucher Cards: 
Desktop:
image

Mobile:
image

Confirmation:
Desktop-splash:
image

Desktop-main:
image

Mobile-main:

image

Closes #99

### CODE REVIEW

**Comment by achhapolia10** [comment]
@adarshsingh87 Can you convert the functional components to class components.

**Comment by achhapolia10** [comment]
@SilverSpear28 Can you please improve the design for order Cards.
Keep only the list but cards in a list. Full-size cards with the following information:
* Date
* Amount
* Promo code applied
* OrderId
* Number of vouchers bought
* A mark of some kind if it was a gift
* Reciever email id and mobile number should also be mentioned

**Comment by adarshsingh87** [comment]
> @adarshsingh87 Can you convert the functional components to class components.

Done.

**Comment by SilverSpear28** [comment]
slight design changes in cards for order page! 

@adarshsingh87 check and do the changes

**Comment by adarshsingh87** [comment]
Desktop:
image

Mobile:
image

**Pull request merged**
